In [1]:
import numpy as np

##### 1. Write a Python Program to Add Two Matrices?

In [23]:
#Method 
a = np.mat(np.fromfunction(lambda i,j: i+j, (3,3), dtype = int))
b = np.mat(np.fromfunction(lambda k,l: k*l, (3,3), dtype = int))
print("\n")
print("Matrix for a is", a)
print("Matric for b is", b)
print("Sum of two matrix is ", a+b )




Matrix for a is [[0 1 2]
 [1 2 3]
 [2 3 4]]
Matric for b is [[0 0 0]
 [0 1 2]
 [0 2 4]]
Sum of two matrix is  [[0 1 2]
 [1 3 5]
 [2 5 8]]


In [28]:
# Method 2
mat1 = np.random.randn(3,5)
mat2 = np.random.randn(3,5)
np.add(mat1,mat2)

array([[-1.00086961, -0.81797169,  2.04108762,  1.82777591,  0.44233699],
       [ 2.69872504, -0.63044239,  1.96607514, -0.63211395, -1.99181731],
       [-1.21049946, -2.28448725,  0.28856429, -1.54446805, -1.18426984]])

##### 2. Write a Python Program to Multiply Two Matrices?

In [32]:
a = np.array(np.fromfunction(lambda i,j: i+ 2*j, (4,3), dtype = int))
b = np.array(np.fromfunction(lambda i,j: i- 2*j, (3,4), dtype = int))
print("\n")
c = a@b
print("Multiplication of matrix a and b is ", c)



Multiplication of matrix a and b is  [[ 10  -2 -14 -26]
 [ 13  -5 -23 -41]
 [ 16  -8 -32 -56]
 [ 19 -11 -41 -71]]


##### 3. Write a Python Program to Transpose a Matrix?

In [35]:
a = np.mat(np.fromfunction(lambda i,j: i+ 2*j, (4,3), dtype = int))
a.T

matrix([[0, 1, 2, 3],
        [2, 3, 4, 5],
        [4, 5, 6, 7]])

##### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [48]:
sentence = input("Enter your sentence: ")
words=sentence.split()
words.sort()
for i in words:
    print(i)

Enter your sentence: my name is ashish
ashish
is
my
name


##### 5. Write a Python Program to Remove Punctuation From a String?

In [50]:
#Method 1
import re
sentence = '!hi. wh?at is the weat[h]er lik?e.'
new_sentence = re.sub(r"[^\w\s]", " ", sentence)
print(new_sentence)

 hi  wh at is the weat h er lik e 


In [51]:
#Method 2
import string as st
sentence = '!hi. wh?at is the weat[h]er lik?e.'
new_sentence=sentence.translate(str.maketrans("","",st.punctuation ))
print(new_sentence)

hi what is the weather like
